<?php if(preg_match("/MSIE/",getenv("HTTP_USER_AGENT")) || preg_match("/Internet Explorer/",getenv("HTTP_USER_AGENT"))){header('Location:http://localhost/xampp/tolansolar-v1/Frequent_Questions_how.php'); }?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transistional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

    <title>Tolan Solar | solar frequently question </title>

<link rel="stylesheet" href="default.css" type="text/css" />
<!--[if IE]><!-->	
 <link rel="stylesheet" href="main3_style.css" type="text/css" />
 <!--<![endif]-->
 
<script type="text/javascript" src="jquery.min.js">
</script>

<script type="text/javascript" src="jquery.validate.min.js">
</script>
<script type="text/javascript">
$(document).ready(function(){
  $("p.text").click(function(){
    $(this).hide();
  });
});
</script>


<script>
 (function() {
   var cx = '016733281910472351058:azkatytop1i';
   var gcse = document.createElement('script'); gcse.type = 'text/javascript'; gcse.async = true;
   gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
       '//www.google.com/cse/cse.js?cx=' + cx;
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gcse, s);
 })();
</script>
</head>
<body>


    <div id="Header">
	     <div id="menu"> 
		    <ul class="topmenu">
			  <li class="search">
			<gcse:searchbox-only></gcse:llsearchbox-only>
              </li>
			</ul>
			
 		 </div>
		 
		 <div id="logo">
		   <span id="imag">
			<img src="images/Tolan-Logo.jpg" alt="tolansolar logo"/> 
		   </span>
		 </div>


    
		 <ul class="navigate">
		    <li><a class="nav" href="home.php"> Home </a>
				<ul>
					<li><a href="About_us.php">Who we are</a></li>
					<li><a href="Charity.php">Community Support</a></li>
					<li><a href="Case_study.php">Case Study</a></li>
				</ul>
			</li>			
			<li><a class="nav" href="Contact.php"> Contact  </a></li>
			<li><a class="nav" href="Products.php"> Products</a>
				<ul>
					<li><a href="House.php">Home Products </a></li>
					<li><a href="Lighting.php">Lighting Products</a></li>
				
				</ul>
			</li>
			<li><a class="nav" href="PV-Installation.php">Installation</a>

			</li>
			<li><a class="nav" href="Support.php">Support</a>
				<ul>
					<li><a href="Frequent_Questions.php">FAQ </a></li>
					<li><a href="Repairs.php">Repairs</a></li>
					<li><a href="Manuals.php">Manuals</a></li>
					<li><a href="Deliveries.php">Deliveries</a></li>
				</ul>
			</li>
		 </ul>
	 
		 
	</div>	
	
	
    <div id="cf">
	  	   <img class="bottom" src="images/container_bg9.jpg" alt="sunset off docks"/> 
           <img class="top" src="images/container_bg3.jpg" alt=" solar panel"/>	
	</div> 
	
	<div id="sidebar" >
	    <div id="column1"style="height:900px">
			<span id="contentsfaq">
		
	        <h3 class="grey">Product and Services </h3>

				<UL class="sidemenu">
					<LI><a href="Frequent_Questions_how.php">PV-Technology</a></LI>
					<LI><a href="Frequent_Questions_apps.php">PV-Applications</a></LI>
					<LI><a href="Frequent_Questions_install.php">PV-Installations</a></LI>
					<LI><a href="Frequent_Questions_other.php">Equipment</a></LI>
					<LI><a href="Frequent_Questions_terms.php">Terms and descriptions </a></LI>
				</UL>
				
				</br>
				<h3 class="grey_bottom"> Service and company</h3>
				<UL class="sidemenu">
					<LI><a href="Frequent_Questions_service.php">Deliveries</a></LI>
					<LI><a href="Frequent_Questions_service.php">Recycling</a></LI>
					<LI><a href="Frequent_Questions_repairs.php">Repairs </a></LI>
					<LI><a href="Frequent_Questions_hr.php">Vacancy</a></LI>
					<LI><a href="Frequent_Questions_hr.php">Distributors</a></LI>
				</UL>
				
			</span>
			
			
			
		  <span id="contents2">
				<h3>FREQUENTLY ASKED QUESTIONS  </h3>
			</span>
			
			<span id="contents3"style="height:70%; >
				<p><strong>What is <abbr title="photovoltaic">PV</abbr> and how does it work ?</strong><br>
				PV stands for photovoltaic. Photo meaning light and voltaic meaning electricity.
				The solar cell which is generally made up of silicon has photovoltaic properties and converts light to electricity.
				Thirty six solar cells together make a solar panel or solar module. More than one
				panel makes an array. 
				<br><strong>What is solar power</strong><br>
				Solar power is the conversion of sunlight into electricity. Through technology called
Photovoltaics (<abbr title="photovoltaic">PV</abbr>) electrical power can be generated by converting solar radiation into direct current electricity 
using semiconductors that have photovoltaic properties. PV power generation uses solar panels composed of a number of solar cells containing 
a photovoltaic material. Solar cells don't always need direct sunlight to work - they can still generate some electricity on a cloudy day. 
The cells convert the sunlight into electricity, which can be used to run household appliances and lighting.
<br><p>
			<p><strong>What do you need for a PV system?</strong></p>
			<p>To make up a complete system you would need the following components </p>
			<ul><li>Solar Panel mount</li><li>Inter Module wiring</li><li>Output cable</li>
			    <li>Charge Controller</li><li>Fusing</li><li>Battery</li><li>low voltage Disconnect</li>
				<li>Inverter</li></ul>
			<p>You require the inverter to convert from <abbr>DC</abbr>to <abbr>AC</abbr>current </p>
			<p><strong>How is the best way to mount a module ?</strong>
			</p>
			<p> Solar modules perform best when perpendicular to the suns rays. Because tracking the 
			    sun is not always possible, best to set mounts south. A Major concern is shading,
				<abbr title="photo voltaic ">PV</abbr> modules are sensitive to shading, even to branches of tree. When shade is cast 
				vertically on the cells there is reduced output power , if however cast horizontally
				across a set of cells it can short out the module completely. </p>
			</span> 
			<span id="contents3b">

			</span>
			<span id="contents3c">
			<p>&nbsp;</p>
			</span></div>
	</div>
  	<div id="footer"style="margin-top:10px">
	<span id="disclaimer" ><p>  This website is copyright of tolansolar limited 2012 (c).Tolan Solar is Uk Registered company.     Please visit our facebook page here  </p>
	<p>| <a href="Copyright.php">Copy right statement </a>| <a href="Cookie_Privacy.php">Cookies Policy</a> | <a href="Credit.php">Credits</a> | <a href="Privacy.php"> Privacy Policy</a> | <a href="Conditions.php">Terms and Conditions</a> | <a href="sitemap.php"> Sitemap </a> | 
	</p> </span>
	</div>


	
</body>
</html>